<a href="https://colab.research.google.com/github/Abhiram-108/CSE-LAB-303/blob/main/Corelationmatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
m, n = 5, 10

In [ ]:
matrix=np.random.randint(10, size=(m, n))


In [ ]:
cov_matrix = np.cov(matrix)

**COV_MATRIX**

In [ ]:
print(cov_matrix)


[[ 8.9         2.96666667  0.97777778 -0.37777778 -3.18888889]
 [ 2.96666667 10.1         0.95555556  3.68888889  5.01111111]
 [ 0.97777778  0.95555556  8.93333333  1.08888889 -0.17777778]
 [-0.37777778  3.68888889  1.08888889  8.62222222  1.97777778]
 [-3.18888889  5.01111111 -0.17777778  1.97777778 10.98888889]]


In [ ]:
std_deviations = np.sqrt(np.diag(cov_matrix))

In [ ]:
correlation_matrix = cov_matrix / np.outer(std_deviations, std_deviations)

***`CORR_MATRIX`***

In [ ]:

print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
[[ 1.          0.3129054   0.10965751 -0.04312527 -0.3224538 ]
 [ 0.3129054   1.          0.1005978   0.3952986   0.47565981]
 [ 0.10965751  0.1005978   1.          0.12407012 -0.01794295]
 [-0.04312527  0.3952986   0.12407012  1.          0.2031847 ]
 [-0.3224538   0.47565981 -0.01794295  0.2031847   1.        ]]
