<a href="https://colab.research.google.com/github/Abhiram-108/CSE-LAB-303/blob/main/covarienceandcorealation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([
    [1, 2, 5],
    [2, 3, 4],
    [3, 4, 3],
    [4, 5, 2],
    [5, 6, 1]
])

In [ ]:
x=x.T


In [ ]:
cov_matrix = np.cov(x, rowvar=False)

In [ ]:
corr_matrix = np.corrcoef(x, rowvar=False)

***COV_MATRIX***

In [ ]:
print(cov_matrix)

[[ 4.33333333  2.         -0.33333333 -2.66666667 -5.        ]
 [ 2.          1.          0.         -1.         -2.        ]
 [-0.33333333  0.          0.33333333  0.66666667  1.        ]
 [-2.66666667 -1.          0.66666667  2.33333333  4.        ]
 [-5.         -2.          1.          4.          7.        ]]


***`CORR_MATRIX`***

In [ ]:
print(corr_matrix)

[[ 1.          0.96076892 -0.2773501  -0.83862787 -0.9078413 ]
 [ 0.96076892  1.          0.         -0.65465367 -0.75592895]
 [-0.2773501   0.          1.          0.75592895  0.65465367]
 [-0.83862787 -0.65465367  0.75592895  1.          0.98974332]
 [-0.9078413  -0.75592895  0.65465367  0.98974332  1.        ]]
