<a href="https://colab.research.google.com/github/Abhiram-108/CSE-LAB-303/blob/main/Naive_Bayes_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Enjoy sports (1).csv')
df.head(10)


Day   Outlook Temp. Humidity    Wind Decision
0    1     Sunny   Hot     High    Weak       No
1    2     Sunny   Hot     High  Strong       No
2    3  Overcast   Hot     High    Weak      Yes
3    4      Rain  Mild     High    Weak      Yes
4    5      Rain  Cool   Normal    Weak      Yes
5    6      Rain  Cool   Normal  Strong       No
6    7  Overcast  Cool   Normal  Strong      Yes
7    8     Sunny  Mild     High    Weak       No
8    9     Sunny  Cool   Normal    Weak      Yes
9   10      Rain  Mild   Normal    Weak      Yes

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()


In [51]:
x=df.drop('Decision',axis=1)
y=df['Decision']
x

Day   Outlook Temp. Humidity    Wind
0     1     Sunny   Hot     High    Weak
1     2     Sunny   Hot     High  Strong
2     3  Overcast   Hot     High    Weak
3     4      Rain  Mild     High    Weak
4     5      Rain  Cool   Normal    Weak
5     6      Rain  Cool   Normal  Strong
6     7  Overcast  Cool   Normal  Strong
7     8     Sunny  Mild     High    Weak
8     9     Sunny  Cool   Normal    Weak
9    10      Rain  Mild   Normal    Weak
10   11     Sunny  Mild   Normal  Strong
11   12  Overcast  Mild     High  Strong
12   13  Overcast   Hot   Normal    Weak
13   14      Rain  Mild     High  Strong

In [53]:
x['Outlook']=le.fit_transform(x['Outlook'])
x['Temp.']=le.fit_transform(x['Temp.'])
x['Humidity']=le.fit_transform(x['Humidity'])
x['Wind']=le.fit_transform(x['Wind'])
y=le.fit_transform(y)

In [54]:
x=x.drop('Day',axis=1)

In [55]:
x

Outlook  Temp.  Humidity  Wind
0         2      1         0     1
1         2      1         0     0
2         0      1         0     1
3         1      2         0     1
4         1      0         1     1
5         1      0         1     0
6         0      0         1     0
7         2      2         0     1
8         2      0         1     1
9         1      2         1     1
10        2      2         1     0
11        0      2         0     0
12        0      1         1     1
13        1      2         0     0

In [56]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()


In [57]:
# model.fit(x,y)

In [58]:
# print("THE ACCURACY OF GIVEN DATA SET")
# # model.score(x,y)

In [59]:
# print("ERROR OF GIVEN DATA SET")
# 1-model.score(x,y)

In [60]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=0
)

In [61]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)
accuray = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")

print("Accuracy:", accuray)
print("F1 Score:", f1)

Accuracy: 0.3333333333333333
F1 Score: 0.16666666666666666


In [63]:
conf_mat = confusion_matrix(
    y_test, y_pred, labels=[0, 1, 2] )

print(accuray)
print(conf_mat)

0.3333333333333333
[[0 0 0]
 [2 1 0]
 [0 0 0]]
